name: continuous-integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist # Adjust the path if your build directory is different

  deploy:
    needs: build # Ensures 'deploy' runs after 'build'
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./dist
      - name: Deploy to EC2
        env:
          EC2_HOST: 65.2.10.58
          EC2_USER: ubuntu
        run: |
          mkdir -p ~/.ssh
          echo "$secrets.PRIVATE_KEY"
          echo "$secrets.PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r ./build $EC2_USER@$EC2_HOST:/home/ubuntu